version: 2.1
setup: true
orbs:
  prodsec: snyk/prodsec-orb@1.0
  orb-tools: circleci/orb-tools@11.5
  shellcheck: circleci/shellcheck@3.1
  bats: circleci/bats@1.1.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-iac
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          exclude: SC2148
          filters: *filters
      - bats/run:
          path: ./src/tests
      - orb-tools/publish:
          orb-name: snyk/driftctl
          vcs-type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check, bats/run]
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
