version: 2.1
orbs:
  driftctl: snyk/driftctl@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5
filters: &filters
  tags:
    only: /.*/
jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test:
    environment:
      DCTL_NO_VERSION_CHECK: "true"
      DCTL_FILTER: "Type=='unknown_type'" # Makes driftctl to exit 0 each time
      AWS_DEFAULT_REGION: "us-east-1"
      DCTL_FROM: "tfstate://tests/terraform.tfstate"
    executor: driftctl/default
    steps:
      - checkout
      - driftctl/install
      - driftctl/scan
  integration-test_install-specific-version:
    environment:
      DCTL_NO_VERSION_CHECK: "true"
    executor: driftctl/default
    steps:
      - checkout
      - driftctl/install:
          version: v0.4.0
      - run:
          name: Verify installed version
          command: driftctl version | grep 'v0.4.0'
      - driftctl/install:
          version: 0.5.0
      - run:
          name: Verify installed version
          command: driftctl version | grep 'v0.5.0'
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - integration-test:
          context: driftctl-acc
          filters: *filters
      - integration-test_install-specific-version:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: snyk/driftctl
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test
            - integration-test_install-specific-version
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
# VS Code Extension Version: 1.4.0
